In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/new-heart-dataset/raw_merged_heart_dataset.csv


In [2]:
df = pd.read_csv('/kaggle/input/new-heart-dataset/raw_merged_heart_dataset.csv')

In [3]:
df.head()

age  sex  cp trestbps chol fbs restecg thalachh exang  oldpeak slope ca  \
0   63    1   3      145  233   1       0      150     0      2.3     0  0   
1   37    1   2      130  250   0       1      187     0      3.5     0  0   
2   41    0   1      130  204   0       0      172     0      1.4     2  0   
3   56    1   1      120  236   0       1      178     0      0.8     2  0   
4   57    0   0      120  354   0       1      163     1      0.6     2  0   

  thal  target  
0    1       1  
1    2       1  
2    2       1  
3    2       1  
4    2       1

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [6]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [7]:
import pandas as pd

# One-hot encode the categorical features in X_train and X_test
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# Align the columns of X_test to match X_train (handles any column mismatch)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [8]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [9]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

# (a) Accuracy_score

In [10]:
from sklearn.metrics import accuracy_score
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.851258581235698
Accuracy of Decision Trees 0.9382151029748284


# (b) Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix

In [12]:
confusion_matrix(y_test,y_pred1)

array([[212,  38],
       [ 27, 160]])

In [13]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0    1
0  212   38
1   27  160

In [14]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0    1
0  234   16
1   11  176

In [15]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [16]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
1487             0                               0                         0
1306             1                               0                         1
785              0                               0                         0
209              0                               0                         0
1157             0                               1                         0
280              0                               0                         0
1353             0                               0                         1
2180             0                               0                         0
492              0                               0                         0
1895             1                               1                         1

# (c) recall_score,precision_score,f1_score

In [17]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [18]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
     0    1
0  212   38
1   27  160
--------------------------------------------------
Precision -  0.8080808080808081
Recall -  0.8556149732620321
F1 score -  0.8311688311688311


In [19]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  234   16
1   11  176
--------------------------------------------------
Precision -  0.9166666666666666
Recall -  0.9411764705882353
F1 score -  0.9287598944591028


In [20]:
precision_score(y_test,y_pred1,average=None)

array([0.88702929, 0.80808081])

In [21]:
precision_score(y_test,y_pred2,average=None)

array([0.95510204, 0.91666667])

In [22]:
recall_score(y_test,y_pred2,average=None)

array([0.936     , 0.94117647])